M48
; DRILL file {KiCad 9.0.4} date 2025-09-01T02:23:11+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-01T02:23:11+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.152
%
G90
G05
T1
X43.251Y-33.353
X46.125Y-37.663
X47.562Y-36.227
T2
X43.0Y-175.0
X143.0Y-33.0
X143.0Y-175.0
M30
